version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: manga-preview-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=your_secure_password
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    restart: always

volumes:
  mongodb_data: 