version: '3.8'
services:
  app:
    build: .
    container_name: manga-preview-app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://admin:your_secure_password@mongodb:27017/manga_preview?authSource=admin
    restart: always

  mongodb:
    image: mongo:latest
    container_name: manga-preview-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=your_secure_password
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    restart: always

volumes:
  mongodb_data: 