name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 依存関係のインストール
      - name: Install dependencies
        run: npm ci

      # ユニットテストの実行
      - name: Run tests
        run: npm test

      # ビルドの実行
      - name: Build application
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()

    steps:
      # コードのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # サーバーに SSH で接続してデプロイ
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # MangaPreviewApp ディレクトリに移動
            cd ~/MangaPreviewApp
            # リモートから最新の変更を取得して反映
            git fetch --all
            git reset --hard origin/main
            # 依存関係のインストール
            npm install --production
            # PM2 プロセスを再起動
            pm2 delete manga-preview-app || true
            pm2 start server/index.js --name "manga-preview-app"
